branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2019

# clone directory
clone_folder: c:\projects\freeablo

platform: x64
configuration: Debug

environment:
  global:
    GITHUB_USER_PASSWORD:
      secure: j7bhatwEDvl5hOfkBHyCIFZdn/x00TkF2qTaJMRn22CJeUr5NhXWPlUepQun7me9
      
install:
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%
  - cmd: pip install requests

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\freeablo
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16 2019" -DFA_TREAT_WARNINGS_AS_ERRORS=ON

build:
  parallel: true
  project: c:\projects\freeablo\build\Freeablo.sln

test_script:
  - cd c:\projects\freeablo\build
  - Debug\unit_tests.exe
